In [33]:
print("hello")

hello

In [34]:
x=3
y=5
x+y

8

<h1> welcome</h1>

In [35]:
x="1.2"
x==12

False

In [36]:
r='20f'

In [37]:
r2=r.rsplit('f')
r2

['20', '']

In [38]:
a=2
b=4
c=a/b
c

0.5

In [39]:
c1=a//b
c1

0

In [40]:
c2=a%b
c2

2

In [41]:
#data structures -list,tuple,dic,set
#list-collection of any datatype;[];mutable
lst=['apple','mango','grapes','watermelon','papaya','jack fruit']
lst

['apple', 'mango', 'grapes', 'watermelon', 'papaya', 'jack fruit']

In [42]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [43]:
lst.insert(4,'orange')

In [44]:
lst.pop(-2)

'papaya'

In [45]:
lst

['apple', 'mango', 'grapes', 'watermelon', 'orange', 'jack fruit']

In [46]:
lst.reverse()

In [47]:
lst

['jack fruit', 'orange', 'watermelon', 'grapes', 'mango', 'apple']

In [48]:
lst.clear()

In [49]:
lst

[]

In [50]:
#tuple immutable|()
tup=('aiems',15,'bidadi',562109.0)
tup

('aiems', 15, 'bidadi', 562109.0)

In [51]:
dir(tuple)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [52]:
#set - no duplicates,{}
st={1,2,3,4,5,6,000}
st

{0, 1, 2, 3, 4, 5, 6}

In [53]:
dir(set)

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [54]:
st1={6,7,8,4,2,34,}
st1

{2, 4, 6, 7, 8, 34}

In [55]:
st.union(st1)
st.intersection(st1)

{2, 4, 6}

In [56]:
#dictionary- k:v|{}| keys are always unique
di={'name':'shravani','age':23}
di

{'name': 'shravani', 'age': 23}

In [57]:
dir(dict)

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [58]:

di.values()

dict_values(['shravani', 23])

In [59]:
di.keys()

dict_keys(['name', 'age'])

In [60]:
'''
guygqgwhjg
sghjgh
sjbhjegh
'''

'\nguygqgwhjg\nsghjgh\nsjbhjegh\n'

In [61]:
#condition statments
#if condition
x=10
if x>=10:
    print('True!')
else:
    print('False!')

True!

In [62]:
marks=55
if marks>=90:
    print('A+')
elif marks >=70 and marks <=89:
    print('A')
elif marks >=60 and marks <=69:
    print('B')
else:
    print('c')

c

In [63]:
for i in range(9):
  print(i)

0
1
2
3
4
5
6
7
8

In [64]:
for a in range(0,11,2):
 print(a)

0
2
4
6
8
10

In [65]:
for a1 in range(1,11,2):
 print(a1)

1
3
5
7
9

In [66]:
#while loop
count=5
while count >=0:
    print(count)
    count=count-1

5
4
3
2
1
0

In [67]:
for i in range(5):
    if i==3:
        continue
    print(i)

0
1
2
4

In [68]:
def funcname():
    return

In [69]:
def addation(a,b):
    return a+b
addation(4,5)

9

In [70]:
def add2(*args):
    return sum(args)
add2(2,3,4,5,6,7,8,9)

44

In [71]:
def greet1():
   print('hello')
greet1

In [72]:
# to install library
%pip install pandas numpy matplotlib seaborn

Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.2.1)
Requirement already satisfied: matplotlib in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (3.10.0)
Requirement already satisfied: seaborn in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [73]:
#data analytics
#improting thr libraries
import pandas as pd
import numpy as np

In [74]:
#load the data set


df = pd.read_csv('Student_Behaviour.csv')
df.head()

,Certification Course,Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,willingness to pursue a career based on their degree,social medai & video,Travelling Time,Stress Level,Financial Status,part-time job
0,No,Male,BCA,100.0,58.0,79.0,65.0,80.0,Video Games,0 - 30 minute,Morning,40000,No,50%,1.30 - 2 hour,30 - 60 minutes,Bad,Bad,No
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
2,Yes,Male,BCA,159.0,78.0,69.5,61.0,55.0,Cinema,1 - 2 Hour,Anytime,13000,Yes,50%,More than 2 hour,30 - 60 minutes,Awful,Bad,No
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
4,No,Male,BCA,170.0,54.0,40.0,65.0,30.0,Video Games,30 - 60 minute,Morning,50000,Yes,25%,1.30 - 2 hour,30 - 60 minutes,Good,good,No

In [75]:
df = pd.read_csv('Student_Behaviour.csv')
df.tail(11)

,Certification Course,Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,willingness to pursue a career based on their degree,social medai & video,Travelling Time,Stress Level,Financial Status,part-time job
224,Yes,Female,Commerce,152.0,65.0,97.0,80.0,100.0,Reading books,3 - 4 hour,Morning,15000,Yes,100%,30 - 60 Minute,0 - 30 minutes,Good,good,Yes
225,Yes,Female,Commerce,164.0,43.0,80.0,89.0,95.0,Reading books,2 - 3 hour,Morning,15000,Yes,100%,1 - 30 Minute,0 - 30 minutes,Good,good,No
226,Yes,Female,Commerce,167.0,65.0,93.0,85.0,90.0,Reading books,1 - 2 Hour,Night,15000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
227,Yes,Male,B.com ISM,167.0,55.0,55.0,57.0,60.0,Sports,30 - 60 minute,Anytime,17000,Yes,25%,0 Minute,0 - 30 minutes,Awful,Bad,No
228,Yes,Male,B.com ISM,155.0,68.0,75.0,75.0,65.0,Sports,1 - 2 Hour,Anytime,500,Yes,100%,1.30 - 2 hour,1 - 1.30 hour,Good,good,No
229,No,Female,B.com ISM,153.0,60.0,60.0,70.0,70.0,Sports,1 - 2 Hour,Anytime,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Good,Bad,No
230,Yes,Male,B.com ISM,170.0,76.0,72.0,67.0,65.0,Video Games,30 - 60 minute,Morning,7000,Yes,50%,More than 2 hour,30 - 60 minutes,Bad,Bad,No
231,Yes,Male,B.com ISM,172.0,52.0,72.0,70.0,76.0,Cinema,2 - 3 hour,Anytime,25000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
232,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,2.30 - 3 hour,Bad,good,No
233,Yes,Female,Commerce,153.0,58.0,85.0,74.0,75.0,Cinema,0 - 30 minute,Anytime,20000,Yes,75%,More than 2 hour,2.30 - 3 hour,Awful,good,No
234,No,Female,B.com ISM,155.0,39.0,45.0,45.0,50.0,Sports,3 - 4 hour,Night,10,No,75%,30 - 60 Minute,2.30 - 3 hour,fabulous,good,No

In [76]:
#to know rows and clm
df.shape

(235, 19)

In [77]:
print ('the no. of rows:{def.shape[0]} and cols:{def.shape[1]}')

the no. of rows:{def.shape[0]} and cols:{def.shape[1]}

In [78]:
df.info

<bound method DataFrame.info of     Certification Course  Gender Department  Height(CM)  Weight(KG)  \
0                     No    Male        BCA       100.0        58.0
1                     No  Female        BCA        90.0        40.0
2                    Yes    Male        BCA       159.0        78.0
3                    Yes  Female        BCA       147.0        20.0
4                     No    Male        BCA       170.0        54.0
..                   ...     ...        ...         ...         ...
230                  Yes    Male  B.com ISM       170.0        76.0
231                  Yes    Male  B.com ISM       172.0        52.0
232                  Yes  Female        BCA       139.0        33.0
233                  Yes  Female   Commerce       153.0        58.0
234                   No  Female  B.com ISM       155.0        39.0

     10th Mark  12th Mark  college mark        hobbies daily studing time  \
0         79.0       65.0          80.0    Video Games      0 - 30 minute
1         70.0       80.0          70.0         Cinema     30 - 60 minute
2         69.5       61.0          55.0         Cinema         1 - 2 Hour
3         70.0       59.0          58.0  Reading books         1 - 2 Hour
4         40.0       65.0          30.0    Video Games     30 - 60 minute
..         ...        ...           ...            ...                ...
230       72.0       67.0          65.0    Video Games     30 - 60 minute
231       72.0       70.0          76.0         Cinema         2 - 3 hour
232       90.0       75.0          70.0         Cinema     30 - 60 minute
233       85.0       74.0          75.0         Cinema      0 - 30 minute
234       45.0       45.0          50.0         Sports         3 - 4 hour

    prefer to study in  salary expectation Do you like your degree?  \
0              Morning               40000                       No
1              Morning               15000                      Yes
2              Anytime               13000                      Yes
3              Anytime             1500000                       No
4              Morning               50000                      Yes
..                 ...                 ...                      ...
230            Morning                7000                      Yes
231            Anytime               25000                      Yes
232              Night               20000                      Yes
233            Anytime               20000                      Yes
234              Night                  10                       No

    willingness to pursue a career based on their degree    \
0                                                  50%
1                                                  75%
2                                                  50%
3                                                  50%
4                                                  25%
..                                                 ...
230                                                50%
231                                                75%
232                                                50%
233                                                75%
234                                                75%

    social medai & video Travelling Time  Stress Level  Financial Status  \
0          1.30 - 2 hour  30 - 60 minutes           Bad              Bad
1          1 - 1.30 hour   0 - 30 minutes           Bad              Bad
2       More than 2 hour  30 - 60 minutes         Awful              Bad
3          1.30 - 2 hour   0 - 30 minutes           Bad             good
4          1.30 - 2 hour  30 - 60 minutes          Good             good
..                   ...              ...           ...              ...
230     More than 2 hour  30 - 60 minutes           Bad              Bad
231       30 - 60 Minute  30 - 60 minutes          Good             good
232       30 - 60 Minute    2.30 - 3 hour           Bad             good
233     More than 2 hour    2.30 - 3 hour         Awful             good
234       30 - 60 Minute    2.30 - 3 hour      fabulous             good

    part-time job
0              No
1              No
2              No
3              No
4              No
..            ...
230            No
231            No
232            No
233            No
234            No

[235 rows x 19 columns]>

In [79]:
df.describe()

,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,salary expectation
count,235.000000,235.000000,235.000000,235.000000,235.000000,2.350000e+02
mean,157.402128,60.803830,76.842128,68.780128,70.660553,3.248168e+04
std,21.510805,14.895844,13.050800,11.016533,15.727446,1.113146e+05
min,4.500000,20.000000,7.400000,45.000000,1.000000,0.000000e+00
25%,152.000000,50.000000,70.000000,60.000000,60.000000,1.500000e+04
50%,160.000000,60.000000,80.000000,69.000000,70.000000,2.000000e+04
75%,170.000000,70.000000,86.250000,76.000000,80.000000,2.500000e+04
max,192.000000,106.000000,98.000000,94.000000,100.000000,1.500000e+06

In [80]:
import pandas as pd
import numpy as np
df = pd.read_csv('Student_Behaviour.csv')
df.head()

,Certification Course,Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,willingness to pursue a career based on their degree,social medai & video,Travelling Time,Stress Level,Financial Status,part-time job
0,No,Male,BCA,100.0,58.0,79.0,65.0,80.0,Video Games,0 - 30 minute,Morning,40000,No,50%,1.30 - 2 hour,30 - 60 minutes,Bad,Bad,No
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
2,Yes,Male,BCA,159.0,78.0,69.5,61.0,55.0,Cinema,1 - 2 Hour,Anytime,13000,Yes,50%,More than 2 hour,30 - 60 minutes,Awful,Bad,No
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
4,No,Male,BCA,170.0,54.0,40.0,65.0,30.0,Video Games,30 - 60 minute,Morning,50000,Yes,25%,1.30 - 2 hour,30 - 60 minutes,Good,good,No

In [81]:
df.columns

Index(['Certification Course', 'Gender', 'Department', 'Height(CM)',
       'Weight(KG)', '10th Mark', '12th Mark', 'college mark', 'hobbies',
       'daily studing time', 'prefer to study in', 'salary expectation',
       'Do you like your degree?',
       'willingness to pursue a career based on their degree  ',
       'social medai & video', 'Travelling Time ', 'Stress Level ',
       'Financial Status', 'part-time job'],
      dtype='object')

In [82]:
df.Gender

0        Male
1      Female
2        Male
3      Female
4        Male
        ...
230      Male
231      Male
232    Female
233    Female
234    Female
Name: Gender, Length: 235, dtype: object

In [83]:
df.iloc[2:5,1:3]

   Gender Department
2    Male        BCA
3  Female        BCA
4    Male        BCA